### PR TITLE
ST3 compatibility

### PR DESCRIPTION
**Pull request by cookieguru**
This fixes the plugin to be compatible with ST3

### CODE REVIEW

**Comment by wbond** [comment]
I'm going to mark this package as ST2-only soon so users aren't confused. If you get this merged in the next day or two, I won't. Otherwise you'll need to open a pull request to https://github.com/wbond/package_control_channel to get it marked as ST3-compatible again.

**Comment by FichteFoll** [comment]
I recommend to just use `universal_newlines=True` instead since this is the generally more correct way:

``` py
output = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, universal_newlines=True).communicate()[0]
```

**Comment by cookieguru** [comment]
It looks like this package was hardcoded to work with the [Sublime Behat Syntax Highlight](https://github.com/omissis/sublime-behat-syntax) by @omissis syntax highlighter.  40cf7e25d51d9a547c02cf3977c3e6eb474d9a9b adds support for the [SublimeText2 Behat Features Syntax Highlight](https://github.com/tomav/SublimeText2-Behat-Features-Syntax) by @tomav syntax highlighter, so the autocomplete functionality will work if either package is installed.

**Comment by cookieguru** [comment]
@jadu seems to be abandoned and I have given up.  Besides, I've switched over to PhpStorm and no longer have a use for this plugin.

**Pull request closed without merging**
